version: "1.0"
services:
  web:
    image: leeing0712/docker-flask:test
    deploy:
      replicas: 5
      resources:
        limits:
          cups: "0.1"
          memory: 50M
        restart_policy:
          condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  # db:
  #   image: mysql
  # redis:
  #   image: redis
  sourcedata:
    image: leeing0712/docker-flask:test
    container_name: source_data
    ports:
      - "5280:80"
    # command: ["python", "app.py"]
    # depends_on: # 解决容器的依赖、启动先后的问题
    #   - db
    #   - redis
    # volumes:
    #   - .:/code # 挂载一个目录或者一个已存在的数据卷容器
    #   - /var/run/docker.sock:/var/run/docker.sock
    # links:
    #   - db
# 网络设置
networks:
  webnet:
driver: bridge